/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

#include <stdio.h>

void print_fib() {
    const int limit = 4000000;
    int a = 1;
    int b = 2;
    int sum = b;

    int i = 0;
    while (b < limit)
    {
        const int temp = b;
        b += a;
        if (++i == 3) {
            sum += b;
            i = 0;
        }
        a = temp;
    }

    printf("Sum = %d\n", sum);
}

int main() {
    print_fib();

    return 0;
}